apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace = "site.shadowcypher.assistant"
    compileSdk = rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId "site.shadowcypher.assistant"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 2
        versionName "1.1"
    }

    signingConfigs {
        release {
            storeFile file("../shadowcypher.keystore")
            storePassword System.getenv("KEYSTORE_PASS")
            keyAlias "shadowcypher"
            keyPassword System.getenv("KEY_PASS")
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    kotlinOptions { jvmTarget = "21" }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:2.1.0"
    implementation "androidx.appcompat:appcompat:$androidxAppCompatVersion"
    implementation "androidx.webkit:webkit:$androidxWebkitVersion"
}
