version: '3.8'

services:
  shadowcypher-ui:
    build: .
    container_name: shadowcypher_mac_engine
    cap_add:
      - NET_RAW
      - NET_ADMIN
    environment:
      - DISPLAY=host.docker.internal:0
      - XAUTHORITY=/.Xauthority
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/.Xauthority:ro
      - ./projects:/opt/ShadowCypher/projects
      - ./payloads:/opt/ShadowCypher/payloads
    command: python3 -m shadowcypher.app
