# fly.toml app configuration generated for shadowcypher-web
app = "shadowcypher-web"
primary_region = "sjc"

[build]
  dockerfile = "./www/Dockerfile"

[env]
  ENVIRONMENT = "production"

[[services]]
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "5s"
    method = "GET"
    path = "/"

[[statics]]
  guest_path = "/srv"
  url_prefix = "/"
