#!/usr/bin/env bash
# shellcheck disable=SC2034

iso_name="shadowos"
iso_label="SHADOWOS_$(date +%Y%m)"
iso_publisher="ShadowCypher <https://shadowcypher.site>"
iso_application="ShadowOS Live/Install Medium"
iso_version="0.1.0-$(date +%Y.%m.%d)"
install_dir="shadowos"
buildmodes=('iso')
bootmodes=('bios.syslinux.mbr' 'bios.syslinux.eltorito' 'uefi-x64.grub.esp')
arch="x86_64"
pacman_conf="pacman.conf"
airootfs_image_type="squashfs"
airootfs_image_tool_options=('-comp' 'zstd' '-Xcompression-level' '3' '-b' '1M')
file_permissions=(
  ["/etc/shadow"]="0:0:0400"
  ["/root"]="0:0:0700"
  ["/root/customize_airootfs.sh"]="0:0:0755"
  ["/usr/local/bin/shadow-stream"]="0:0:755"
  ["/usr/local/bin/shadow-wipe"]="0:0:755"
  ["/usr/local/bin/shadowos-firstboot"]="0:0:755"
  ["/usr/local/bin/shadowos-session-start"]="0:0:0755"
  ["/usr/local/bin/shadow-mode"]="0:0:0755"
  ["/usr/local/bin/shadow-bios"]="0:0:0755"
  ["/usr/local/bin/shadow-mode-bar"]="0:0:0755"
  ["/usr/local/bin/shadow-score"]="0:0:0755"
  ["/usr/local/bin/shadow-ai-overlay"]="0:0:0755"
  ["/usr/local/bin/shadowos-install"]="0:0:0755"
  ["/usr/local/bin/shadowos-welcome"]="0:0:0755"
  ["/etc/shadowos/modes/gaming/apply.sh"]="0:0:0755"
  ["/etc/shadowos/modes/gaming/revert.sh"]="0:0:0755"
  ["/etc/shadowos/modes/pentest/apply.sh"]="0:0:0755"
  ["/etc/shadowos/modes/pentest/revert.sh"]="0:0:0755"
  ["/etc/shadowos/modes/privacy/apply.sh"]="0:0:0755"
  ["/etc/shadowos/modes/privacy/revert.sh"]="0:0:0755"
  ["/etc/shadowos/modes/ghost/apply.sh"]="0:0:0755"
  ["/etc/shadowos/modes/ghost/revert.sh"]="0:0:0755"
  ["/etc/shadowos/modes/normal/apply.sh"]="0:0:0755"
  ["/etc/shadowos/modes/dev/apply.sh"]="0:0:0755"
  ["/etc/shadowos/modes/undercover/apply.sh"]="0:0:0755"
  ["/etc/shadowos/modes/_network_open.sh"]="0:0:0755"
  ["/etc/skel/.ssh"]="0:0:0700"
)
