font=JetBrainsMono Nerd Font:size=12
font-bold=JetBrainsMono Nerd Font:weight=bold:size=12
font-italic=JetBrainsMono Nerd Font:slant=italic:size=12
dpi-aware=auto
pad=14x14
initial-window-size-chars=110x32
title=foot
locked-title=no
selection-target=clipboard
word-delimiters=,│`|:"'()[]{}<>

[main]
shell=/usr/bin/zsh
login-shell=no

[scrollback]
lines=20000
multiplier=3.0
indicator-position=relative

[url]
launch=xdg-open ${url}
osc8-underline=url-mode
protocols=http, https, ftp, ftps, file, gemini, gopher

[cursor]
style=beam
beam-thickness=1.6
blink=yes

[mouse]
hide-when-typing=yes

[key-bindings]
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste
search-start=Control+Shift+r
font-increase=Control+plus Control+equal Control+KP_Add
font-decrease=Control+minus Control+KP_Subtract
font-reset=Control+0 Control+KP_0

[colors]
alpha=0.88
foreground=E6EDF3
background=05080C
selection-foreground=06090D
selection-background=00E0A4

# Normal
regular0=11161D
regular1=FF6B6B
regular2=00E0A4
regular3=FFC857
regular4=6BA8FF
regular5=C792EA
regular6=7ADBE0
regular7=C9D1D9

# Bright
bright0=3D4651
bright1=FF8B8B
bright2=5BFFD1
bright3=FFD787
bright4=8FC0FF
bright5=DDB0FF
bright6=A8EBEF
bright7=E6EDF3
