name = "shadowcypher-releases"
main = "src/index.ts"
compatibility_date = "2026-04-26"

[[routes]]
pattern = "releases.shadowcypher.site"
custom_domain = true

[[r2_buckets]]
binding = "SHADOW_FILES"
bucket_name = "shadowcypher-files"
