---
modules-search: [ local, /usr/lib/calamares/modules ]

instances:
- id:     before_bootloader
  module: shellprocess
  config: shellprocess_before_bootloader.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - initcpio
  - shellprocess@before_bootloader
  - grubcfg
  - bootloader
  - umount
- show:
  - finished

branding: shadowos

prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
