# ShadowOS kernel hardening
kernel.randomize_va_space = 2
kernel.kptr_restrict = 2
kernel.yama.ptrace_scope = 2
kernel.unprivileged_bpf_disabled = 1
net.core.bpf_jit_harden = 2
kernel.perf_event_paranoid = 3
vm.mmap_min_addr = 65536
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.all.rp_filter = 1
net.ipv6.conf.all.accept_redirects = 0

# Base performance (gaming mode overrides swappiness to 10)
vm.swappiness = 30
vm.dirty_ratio = 15
vm.dirty_background_ratio = 3
vm.max_map_count = 524288
vm.vfs_cache_pressure = 75
kernel.dmesg_restrict = 1
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
net.ipv4.tcp_syncookies = 1
