[Theme]
Current=shadowos
CursorTheme=Adwaita
Font=JetBrainsMono Nerd Font

[Wayland]
SessionDir=/usr/share/wayland-sessions

[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell

[Autologin]
Relogin=false
